apiVersion: v2
appVersion: 2.11.2
description: A Helm chart for multicluster-engine - CRDs
keywords:
- mce
- multicluster-engine
- multiclusterengine
name: multicluster-engine-crds
sources:
- quay.io/redhat-user-workloads/crt-redhat-acm-tenant/mce-operator-bundle-mce-211@sha256:cc172dd831ce24c411a7e0ddb8604d3e83143fafa7af6a27603775940afd6720
type: application
version: 2.11.2
